### ISSUE TITLE
RNA-seq data(Plant)

### ISSUE THREAD

**Issue by zjDzlll** [stefpeschel/NetCoMi#111]
Hi @stefpeschel 
Very good software!!!
I have one question. Can this software be used for comparison networks of RNA seq data (different materials in the same environment)?

**Comment by stefpeschel** [comment]
Hi,
The package is generally applicable to any kind of count data, and especially to data where compositionality is an issue. In NetCoMi, the rows and columns are called samples and taxa because it was designed for microbiome data. However, it can also be used to generate gene-gene networks, for example. To estimate associations, you could use, e.g., the SPRING approach, or follow standard RNA-seq pipelines and pass the association matrix directly to the netConstruct function.
