### ISSUE TITLE
Cross domain interactions

### ISSUE THREAD

**Issue by TeeratatK** [stefpeschel/NetCoMi#115]
It is a short question. Is it practical for cross domain interactions as SpiecEasi package?

**Comment by stefpeschel** [comment]
You can generate the association matrix using SpiecEasi and use NetCoMi for network analysis and plotting as described [here](https://github.com/stefpeschel/NetCoMi/blob/main/tutorials/TUTORIAL_cross-domain_associations.md).

**Comment by TeeratatK** [comment]
Thank you for replying to my question. I'm working with 2 phyloseq objects that contain ITS data and Metabolite data, and I merged them into one object named "fun.bac.merge.renamed". I would like to ask you if I pass association matrix creation using SpiecEasi and use "measure = measure = "spieceasi" " instead. What is the different result that will be compared to the above tutorial? 

# Network construction and analysis
net_genus <- netConstruct(fun.bac.merge.renamed,
                           measure = "spieceasi", #Association measures
                           measurePar = list(nlambda=10, lambda.min.ratio = 1e-2),
                           normMethod = "clr",
                           zeroMethod = "none",
                           sparsMethod = "none",
                           thresh = 0.3, #Defult
                           verbose = 2
                            )

**Comment by stefpeschel** [comment]
Passing the association matrix to `netConstruct()` and setting measure to "spieceasi" won't work, because that would mean you are estimating associations from an association matrix, which doesn't make sense. 

You have two options: 
- Estimate the association matrix in advance with `SpiecEasi` and pass the matrix to `netConstruct()` as explained in the tutorial. 
Here you have to set `dataType` to "condDependence" (or just "correlation"; there's currently no difference). 
- Pass your phyloseq object to `netConstruct()` and set measure to "spieceasi" so that associations are estimated within `netConstruct()`. In this case, the `dataType` must be "counts". 

The latter won't work if you want to do a cross-domain analysis, so I recommend following my tutorial, which covers exactly your use-case.
