### ISSUE TITLE
How to include 16s and ITs data similar to as SpiecEasi

### ISSUE THREAD

**Issue by ramay** [stefpeschel/NetCoMi#12]
Hi,
Thank you for a very useful package!
I was trying to figure out if I could include 16s and ITS data like in SpiecEasi in NetCoMi. Is it possible?

https://github.com/zdk123/SpiecEasi#cross-domain-interactions

Hena

**Comment by muellsen** [comment]
Hej Hena, thanks for the positive feedback, and cool that you use NetCoMi. We are working on this issue and will include it in a future version, hopefully. For now, the simplest solution is to use SpiecEasi for the learning part, and then load the resulting networks from SpiecEasi into NetCoMi, and use NetCoMi's functionalities for the downstream analysis. @stefpeschel can maybe clarify as well.
Thanks, Christian

**Comment by ramay** [comment]
Thanks @muellsen ! I will try it out.
Hena

**Comment by stefpeschel** [comment]
Hey Hena, 
I'm pleased that you are interest in using NetCoMi!
As @muellsen wrote, currently the only way to perform a cross-domain network analysis is to use the SpiecEasi package for estimating the associations and pass them to NetCoMi's netConstruct() function using the arguments "data" and "data2". In this case, the argument "dataType" must be set to "partialCorr". 
Please let us know if you have any questions or problems. 
Best wishes
Stefanie

**Comment by ramay** [comment]
Thanks @stefpeschel ! I am a little bit confused. I ran spiec.easi function with the two data types but I am not sure what am I passing onto netConstruct from speciecEasi or how am I passing them on like which variable in netconstruct gets the output of spiecEasi. Sorry I am new to this and need more help.

Hena

**Comment by ramay** [comment]
So this is what I have done from what I understood from the  messages:
First pass the bacterial phyloseq object to the spiec.easi function
`ps1<-spiec.easi(ps, method='mb', nlambda=40,
+                      lambda.min.ratio=1e-2, pulsar.params = list(thresh = 0.05))`

Same for fungal phyloseq object
`psf1<-spiec.easi(psf, method='mb', nlambda=40,
+                      lambda.min.ratio=1e-2, pulsar.params = list(thresh = 0.05))`

and then pass these two objects to netconstruct
`netConstruct(data = ps1 ,data2 = psf1, dataType = "partialCorr")`
error is
`Error in condition_handling(dataType = dataType, assoType = assoType,  : 
  Sample size necessary for Student's t-test.`

What am I doing wrong?

Thanks
Hena

**Comment by fconstancias** [comment]
Dear NetCoMi developers,

Thanks for this promsing package. I am also interested in cross domain-network and got a bit confused.

I first constructed the cross-domain network as explained [there](https://github.com/zdk123/SpiecEasi#cross-domain-interactions) : 

```
require(SpiecEasi)
net <- spiec.easi(list(phylo_16S, phylo_ITS), method='mb', nlambda = 40,
                      lambda.min.ratio=1e-2, pulsar.params = list(thresh = 0.05, ncores = 6))
```

I am not sure what you mean with "NetCoMi's netConstruct() function using the arguments "data" and "data2"" since one network was infered from the two domains combined.

I tried the following without success:

```
require(NetCoMi)
netConstruct(data = net,
             measure = "spieceasi",
             dataType = "partialCorr") -> multi_test
```


```
netConstruct(data = net, data2 = list(phylo_16S, phylo_ITS),
             measure = "spieceasi",
             dataType = "partialCorr") -> multi_test
```

Both commands gave me the same error as @ramay :

`Error in condition_handling(dataType = dataType, assoType = assoType, : Sample size necessary for Student's t-test.`

What are we missing here? Thanks in advance for the support.

**Comment by stefpeschel** [comment]
Thanks Florentin for using NetCoMi!

I just uploaded a tutorial on how to compare cross-domain association networks using NetCoMi in combination with SpiecEasi's functionality for estimating cross-domain associations. You can find it in the "tutorials" folder. 

Sorry for the confusion with "data" and "data2". My statement referred to the case where two networks are compared. Then, the cross-domain network for group 1 must be passed to "data" and that for group 2 to "data2". 

I suppose, you want to perform the cross-domain network analysis only for a single network. In this case you won't need the "data2" argument. 

Regarding the error that the sample size is needed: In this combined approach with SpiecEasi and NetCoMi, the "sparsMethod" argument must be set to "none" since sparsification is already included in SpiecEasi. 
In the standard approach with a count matrix and association measure as input, the sparsMethod argument is automatically set to "none" for spieceasi, however, if an association matrix is used as input, this argument must be set correctly. 

Best wishes, 
Stefanie

**Comment by fconstancias** [comment]
thanks Stefanie
