### ISSUE TITLE
input for net construct()

### ISSUE THREAD

**Issue by nandhu1705** [stefpeschel/NetCoMi#132]
Hi,
Just a basic question before I start the analysis. netConstruct would need the raw counts for analysis right?. Then it apply CLR normalization and it would take the normalized counts for the network construction right? 

after CLR normalization, will netConstrust convert it to relative abudance or will it keep the CLR normalized counts to build the network analysis. ?
net_pears <- netConstruct(amgut2.filt.phy,  
                          measure = "pearson",
                          normMethod = "clr",
                          zeroMethod = "multRepl",
                          sparsMethod = "threshold",
                          thresh = 0.3,
                          verbose = 3)

**Comment by stefpeschel** [comment]
Yes, exactly. 
[Here](https://microbiome.github.io/OMA/docs/devel/pages/network_learning.html) is an illustration of the workflow performed inside netConstruct(), only that you would use multiplicative replacement instead of pseudo counts. 

Neither relative abundances nor clr transformed counts are used for network analysis, because the clr transformed counts are used to estimate correlations. These correlations are then transformed into similarity values / edge weights on which the network analysis and plot are based.
