### ISSUE TITLE
replacement has length zero error

### ISSUE THREAD

**Issue by lixiaopi1985** [stefpeschel/NetCoMi#17]
Hi,

Thank you for developing this tool, it really facilitates the network analyses. I encountered an error:

```
> stat_SvsR = netCompare(netAn_SvsR, permTest = T, seed = 101, cores = 2)
Calculate network properties ... Done.
Execute permutation tests ... 
  |====================================================================| 100%Error in { : task 157 failed - "replacement has length zero"
```
Is it because the sample sizes are different between the two?

Thank you,

```
# split phyloseq object 
endo.split <- metagMisc::phyloseq_sep_variable(endo, 
                                                "Resistance")
endo.split$R # 2216 taxa and 97 samples
endo.split$S # 1990 taxa and 23 samples


net_SvsR = netConstruct(endo.split$S, endo.split$R,
                        filtTax = "highestFreq",
                        filtTaxPar = list(highestFreq = 100),
                        filtSamp = "totalReads",
                        filtSampPar = list(highestFreq = 1000),
                        zeroMethod = "none", 
                        normMethod = "none",
                        measure = "spring",
                        measurePar = list(nlambda = 10, rep.num = 10),
                        dissFunc = "signed",
                        sparsMethod = "none",
                        verbose = 3,
                        seed = 111)


# analysis

netAn_SvsR = netAnalyze(net_SvsR,
                        centrLCC = FALSE,
                        avDissIgnoreInf = TRUE,
                        sPathNorm = F, 
                        clustMethod = "cluster_fast_greedy",
                        hubPar = c("degree", "between", "closeness"),
                        hubQuant = 0.9,
                        weightDeg = FALSE,
                        lnormFit = TRUE,
                        normDeg = F,
                        normBetw = F,
                        normClose = F,
                        normEigen = F)
```

**Comment by stefpeschel** [comment]
Dear Xiaoping,
Thanks for using NetCoMi and your positive feedback!

The sample sizes don't need to be equal, however, you should have in mind that comparability of the two networks is not ensured if the sample sizes differ strongly. 

I think I've been able to reproduce the error with another data set. I get the error `replacement has length zero` if one of the "permuted" association matrices is empty (all estimated associations are exactly zero). I assume, in your case, this happens due to the low sample size in the "R" group. 
So, I'll rework the network comparison workflow and include an appropriate handling of empty permutation matrices. 

Please rerun your code as soon as NetCoMi is updated and let me know whether the error still occurs in your setting. 

Furthermore, please note that the `filtSampPar` argument has not been set correctly in your example. If you want to exclude samples with a total number of reads below 1000, the arguments must be set as follows:

```
net_SvsR = netConstruct(endo.split$S, endo.split$R,
                        filtTax = "highestFreq",
                        filtTaxPar = list(highestFreq = 100),
                        filtSamp = "totalReads",
                        filtSampPar = list(totalReads= 1000),
                        ... )
```
Thanks, Stefanie

**Comment by ilapt** [comment]
Hi there,
I have the same exact problem. I also tried to agglomerate data an re-run at species or higher taxonomic levels, but I always end up with the following error message:

Calculate 'spring' associations ... 
Error in hatRupper[-ind_cutoff] <- bridgeInv(Kupper[-ind_cutoff], zratio1 = zratio1vec[-ind_cutoff],  : 
  replacement has length zero

My sample sizer in the two groups are 98 vs 58.

Thank you for this valuable tool and for your kind help!
Ilaria

**Comment by stefpeschel** [comment]
Hi Ilaria,

The developers of mixedCCA did some tests but could not reproduce your error. Could you please send me a reproducible example with data (maybe an anonymized small subset of your data) via email so that we can figure out where the error comes from?

Thanks!
Stefanie

**Comment by stefpeschel** [comment]
@ilapt: I figured out where the error comes from. There is a current issue with the fast latent correlation computation in [mixedCCA](https://github.com/irinagain/mixedCCA), which is used by the [SPRING](https://github.com/GraceYoon/SPRING) package. The SPRING parameter `Rmethod` must be set to "original" until the issue is solved. I just uploaded a release (version 1.0.3), where the issue is fixed. Please update NetCoMi to the latest version to solve the problem. 

Thanks,
Stefanie
