### ISSUE TITLE
Error in update.list(rep.num = 20, criterion = "stars", thresh = 0.05, : argument "new" is missing, with no default

### ISSUE THREAD

**Issue by Danread** [stefpeschel/NetCoMi#5]
When running the example workflow, I get the error "Error in update.list(rep.num = 20, criterion = "stars", thresh = 0.05, : argument "new" is missing, with no default" when using netConstruct

**Comment by stefpeschel** [comment]
The error is caused by a conflict of SpiecEasi and the gdata package. 

NetCoMi depends on the _metagenomeSeq_ package (used for the CSS normalization method) and _metagenomeSeq_, in turn, depends on the _gplots_ package. An older version of _gplots_ was dependent on _gdata_, so that the error occurs if an old _gplots_ version (2.3.2 in my case) is installed. 

To solve this error, please update the gplots package (>=3.1.0) and remove _gdata_ from your library.

For those who want further information on how the error is caused: 
In _spiec.easi.default()_, the following expression is called:

call <- do.call('update', c(pulsar.params, list(object=list(call=call), evaluate=FALSE)))

which should call _update.default()_. However, the gdata package contains a function _update.list()_, which is called instead and causes the error.
