### ISSUE TITLE
Problem of installing netcomi package 

### ISSUE THREAD

**Issue by rusher321** [stefpeschel/NetCoMi#56]
When I installed the package and followed  the guideline, I occured an error like below

```
Error: Failed to install 'unknown package' from GitHub:
  Failed to install 'unknown package' from GitHub:
  HTTP error 403.
  API rate limit exceeded for  XXX.XXX.XXX. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)

  Rate limit remaining: 0/60
  Rate limit reset at: 2022-07-11 10:22:13 UTC

```

Is it a common problem?
I tried to add the github token,  but not solve it ~

**Comment by rusher321** [comment]
I have installed the package as your commend the manual option. I guess can add it in the readme file.

**Comment by stefpeschel** [comment]
Hey, 
This doesn't seem to be a NetCoMi issue but a general problem with GitHub or devtools::install_github so that you're not able to install packages from GitHub. 

Maybe you'll find some help [here](https://www.google.de/search?q=github+%22api+rate+limit+exceeded%22&source=hp&ei=mTLNYuCjB-qBxc8P2s-5uAk&iflsig=AJiK0e8AAAAAYs1AqWSEJdRYG7DGF2JaaTVtflfepDXV&ved=0ahUKEwig1MOK-fL4AhXqQPEDHdpnDpcQ4dUDCAg&uact=5&oq=github+%22api+rate+limit+exceeded%22&gs_lcp=Cgdnd3Mtd2l6EAMyBAgAEBMyBAgAEBMyBAgAEBMyBAgAEBMyCAgAEB4QFhATMggIABAeEBYQEzIICAAQHhAWEBMyCggAEB4QFhAKEBMyCAgAEB4QFhATUABYns0BYKbUAWgFcAB4AIABfYgB1gKSAQMzLjGYAQCgAQKgAQGwAQA&sclient=gws-wiz)

Best,
Stefanie

**Comment by rusher321** [comment]
Hey Stefanie,

Thanks for your response. 
Yes, it indeed occurred by the limit of Github. I also found some guys have pushed the same issue. I think it would be better if give some clues about it on the homepage. 
Also, thanks for your package,  I'm now using it to do the network analysis~ 

Best 
Huahui
