### ISSUE TITLE
conditional dependence

### ISSUE THREAD

**Issue by gc26762524** [stefpeschel/NetCoMi#58]
Hello NetCoMi developer,

Please allow me to create this issue, with extensive reading/googling in recent days, I just feel here might be the best place to ask this question.

In a manuscript we get for revision, where essentially we constructed two networks (case & control), and then made some basic comparisons about the common/different edges and node-pairs in the study. we get a review question "For the whole network analysis unless the datasets really are the same size - the same number of samples, and the same set of features - then the presence of an edge in one network but not the other is risky to conclude anything from. I would instead propose to build the network from all samples and add an interaction term between edge and disease status, then look for edges where this interaction term is significant. Either way, I would need more certainty that this part is not subject to artifacts before I can assess the network results."

My questions are 
1. do you agree that "the same number of samples" is the prerequisite for a fair network comparison? (assuming the two networks have the same domain/nature of course). In the NetCoMi examples amgut_split$no & yes, they don't have the same number of samples either, and so in many other published network comparison papers.
2. I agree with the reviewer that pointed out a single network should be built first and then compares the condition. I would wonder if we could just use netConstruct() function for building two networks and then do the comparison using TUTORIAL_createAssoPerm tutorial (or netCompare()?) to address the "interaction" issue. Is this basically what you referred to in your paper about the "conditional dependence"? I am not quite clear on the term.

Any suggestions will be very appreciated. Thank you a lot in advance.

Cheng

**Comment by stefpeschel** [comment]
Dear Cheng, 

Thank you for reaching out to us. 

Constructing a single network and including the disease status would be an option to assess the association between microbes and the disease status. However, a network comparison between cases and controls or two environmental states is a valid approach to find microbes that are differentially associated between two groups and to reveal differences in the network structure. This approach is common practice, see e.g., [Sommer et al. [2022]](https://journals.plos.org/ploscompbiol/article?id=10.1371/journal.pcbi.1010044). Comparing two networks allows, for instance, to assess whether microbes cluster differently between the groups, or whether keystone taxa (expressed by hub nodes) are different.

The sample size issue is a legitimate point, which we mention in the discussion of our manuscript. [Fisher [1921]](https://hekyll.services.adelaide.edu.au/dspace/bitstream/2440/15169/1/14.pdf) has shown that the sample correlations $r$ vary around the true, unobserved correlation coefficient $\rho$ with a variance that is dependent on the sample size as well as on $\rho$ (see i.e., Figures 1 and 2 in Fisher, [1921]).  

Here is an example of why this is problematic: 
Imagine the data set is split into two groups and the true population correlations are close to 0 for most taxa pairs. According to Fisher [1921], the sample correlations are nearly normal distributed if $\rho$ is close to 0. Let the sample size of group 1 be considerably smaller than that of group 2, then the variance of estimated correlations is larger in group 1. If we chose a threshold of |±0.3| in group 1, more taxa pairs would be expected to be connected in the network, just because of their greater variance. This may lead to spurious results when network properties are compared between the two groups.

This issue can be addressed to some extent by using Student’s t-test as sparsification method. However, for considerably different sample sizes – especially if one group is particularly small – the sample size is still an issue. 

The interplay between association estimates, normalization, and sample size is examined and greatly illustrated in [Badri et al. [2020]](https://doi.org/10.1093/NARGAB/LQAA100). The authors show that shrinkage leads to association estimates that are nearly independent of sample size, which would be a necessary behavior to be comparable between groups. Since shrinkage is not yet implemented in NetCoMi, (nearly) equal sample sizes would be important for a reliable network comparison.

As for your second question, I would like to clarify two terms:
- “Interaction”, as stated by the reviewer, is actually the wrong term because "interaction" in the statistical sense means something different. “Association” would be appropriate to express relations between taxa and the disease state. 
- "Conditional dependence" is one of the available measures to express associtiations between microbes. In contrast to correlation, conditional dependence expresses direct relations between each two components.  Estimating associations between microbes and the disease variable (and including them in the network) is a different topic, which is not implemented yet but planned for future NetCoMi versions. 

The “createAssoPerm” tutorial is not related to your issue. It explains how to estimate permutation associations outside netConstruct(), which might be useful for large data sets. 

Best,
Stefanie

**References:**

- Badri, M., Kurtz, Z. D., Bonneau, R., & Müller, C. L. (2020). Shrinkage improves estimation of microbial associations under different normalization methods. NAR Genomics and Bioinformatics, 2(4). https://doi.org/10.1093/NARGAB/LQAA100
- Fisher, R. A. (1921). On the “probable error” of a coefficient of correlation deduced from a small sample. Metron, 1, 3–32.
- Sommer, A. J., Peters, A., Rommel, M., Cyrys, J., Grallert, H., Haller, D., … Bind, M.-A. C. (2022). A randomization-based causal inference framework for uncovering environmental exposure effects on human gut microbiota. PLOS Computational Biology, 18(5), e1010044. https://doi.org/10.1371/journal.pcbi.1010044

**Comment by gc26762524** [comment]
Hi Stefanie,

Thank you so much for the clarification and explanation. I have read through all the information and reference materials you provided that I am able to get a good sense of your answer and I am clear now.

Again, thank you. I will continue to use your fantastic tool and recommend NetCoMi to my friends. Wish you a good day there.

Best,
Cheng

**Comment by indrikwijaya** [comment]
Hi, 

Sorry to reopen this issue. But, I'm curious on how do we address the issue of having very different sample sizes between the 2 groups. Do we subsample the larger group so that the number of samples between the 2 groups will be equal? So, if we're using `t-test`, the `sampleSize` parameter in `NetConstruct` will be equal to the size of the smaller group?

**Comment by stefpeschel** [comment]
Hi, 
Yes you can randomly subsample from the larger group. The `sampleSize` argument expects a vector with one or two elements. If the sample sizes are equal, you can give just a single value, which will be used for both groups.
