### ISSUE TITLE
Multiple sample group comparison

### ISSUE THREAD

**Issue by npechl** [stefpeschel/NetCoMi#76]
Hi @stefpeschel,

I am trying to use `NetCoMi` for 16S microbiome data. I am really interested in investigating the results coming from `netCompare` and `diffnet` functions. My problem is that I do not have only two groups of samples, but multiple groups. 

**Is there an option for multiple group testing/comparison?** A possible solution would be to construct each network separately and then do the comparison, but this is going to take a lot of time in order to be completed.

Thank you in advance for your time!

Regards, 
Nikos

PS: Really nice work with the `NetCoMi` package. I am a big fan of the `SpiecEasi` algorithm, but I think i will start using `NetCoMi` from now on!

**Comment by stefpeschel** [comment]
Hi Nikos, 
Thanks a lot for your feedback!

Unfortunately, NetCoMi can only compare two networks because for each network measure, the difference between the two groups is computed and tested for significance. Comparing and testing more than two measures would be more complicated.

So, the only option is to construct each network separately. You can, however, use the same layout for all network plots to compare the networks at least visually. This is done by storing the network output to a variable and reusing the layout in further plots:
```
# Network plot of the first group
p <- plot(netprops1, ...)

# Further network plots
plot(netprops2, layout = p$layout, ...)
plot(netprops3, layout = p$layout, ...)
...
```

Best,
Stefanie

**Comment by npechl** [comment]
Thank you for your answer Stefanie @stefpeschel (and for your suggestion)!
I think the issue should be closed.

Nikos
