### ISSUE TITLE
Compare two conditions in one network

### ISSUE THREAD

**Issue by linux51** [stefpeschel/NetCoMi#86]
Good morning, Thank you for the good package. I have phyloseq object of control and disease group. I did try separate control group and disease group then construct the network. But i would like to see the dynamic changes from control to disease in one network. Would you please provide me some guideline?

**Comment by stefpeschel** [comment]
Hey, 
you can follow [this tutorial on cross-domain networks](https://github.com/stefpeschel/NetCoMi/blob/main/tutorials/TUTORIAL_cross-domain_associations.md) and use your disease and control data sets instead of the two domains. The tutorial explains, how two cross-domain networks are compared. Since you want to construct a single network, you can skip the step where the data is split into two groups. 
Best regards,
Stefanie

**Comment by linux51** [comment]
Thank you
