### ISSUE TITLE
Multithreading not working

### ISSUE THREAD

**Issue by bioInfoGirl** [stefpeschel/NetCoMi#89]
Hi ! 
I'm using netConstruct with a relatively large phyloseq object as an input, and I've tried to use the cores parameter to make the process faster, but it still using 1 core on my computer (I'm on windows with an AMD Ryzen 7 processor). Do you know what might be the issue ?

This is my command line as an exemple (I've loaded the parallel library) : 
netConstruct(data,
                      taxRank = "Genus",
                      filtTax = "totalReads",
                      filtTaxPar = list(totalReads = 2),
                      zeroMethod = "none",
                      normMethod = "none",
                      seed = 100,
                      cores = 8)

Thank you :)
P.S. This package is really useful it's really appreciated !

**Comment by stefpeschel** [comment]
Hi @bioInfoGirl,

Thanks for using NetCoMi!

The `cores` argument is used only when sparsification is done by bootstrapping, as described in the help page of `netConstruct()`. So, in your case, the argument will be ignored.

You might consider using a different association measure. You're currently using the default, which is SpiecEasi. You could use "spring" (the SPRING approach) instead, which also estimates partial correlations, but is faster for large count matrices. Just make sure you're using the latest NetCoMi version so that the SPRING parameter `Rmethod` is set to "approx" by default. 

Best,
Stefanie
