### ISSUE TITLE
Networks with multiple conditions

### ISSUE THREAD

**Issue by andressamv** [stefpeschel/NetCoMi#90]
Hi, I have been using NetCoMi for a while now, and it is such a great package (thank you!). I am working on a new project in which I have more than six conditions (A, B, C, D, E, F) that I would like to test. Initially, we used the scripts for comparing two of the six treatments, but every time we established these pairwise comparisons, the networks changed (for example, network A from the A vs. B comparison is different from network A from the A vs. C comparison). I don't understand why this is happening. What is the best way to compare different networks in my case? Producing each one of them separately? Thanks!

**Comment by stefpeschel** [comment]
Hi,
Thanks for using NetCoMi!

I assume that by "the networks have been changed" you mean that the layout is different between the plots, so that they are not comparable. 

I'd suggest constructing each network separately and using the same layout for all plots. In issue [#76](https://github.com/stefpeschel/NetCoMi/issues/76), I already gave an example. 

Let me know if you have any more questions. 

Best,
Stefanie
