### ISSUE TITLE
saving a plot

### ISSUE THREAD

**Issue by hyoj-seo** [stefpeschel/NetCoMi#99]
Thank you for making a great program!

Following the tutorial, I created a network using Pearson.

However, the image created through plot() cannot be saved in an environment where you are using a remote connection using a jupyter notebook.

I tried using pdf() + dev.off() and ggsave() but failed.

The local Rstudio succeeded in resizing and saving the image with the Rstudio's image function, but the current environment requires a way to save it in the jupyter notebook.

![image](https://github.com/stefpeschel/NetCoMi/assets/89058101/cccd6285-7d36-4398-b4d0-cbd3285921ba)

In the preview of the jupyter, the image looks truncated, so it is essential to save after resizing the image.

Would you be so kind as to offer your assistance?
I express my gratitude in advance
HJ

**Comment by stefpeschel** [comment]
Hi, 
Have you tried changing the `width` and `height` arguments of the `pdf()` function? In general, the larger the size, the better the network will fit into the plot area. For R Markdown, which I work with, it's the same.
In addition, NetCoMi's plot function has a `mar` argument to define the margins. You can increase the right margin so that the legend fits into the plotting region.
Best,
Stefanie
